# -*- coding: utf-8 -*-
"""CS4200-lab 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c_43tBrHtRS0MQlqDSE6FzbVrcqDF8G8
"""

import torch
import torchvision
import torch.nn as nn
import argparse
import PIL
import random

# TODO 1: Choose a digit
digit = 6

# TODO 2: Change number of training iterations for classifier
n0 = 50

def to_list(img):
    return list(map(int, img.view((28*28,)).tolist()))
    
SCALE_OFF = 0    
SCALE_RANGE = 1
SCALE_01 = 2
    

def show_image(tens, imgname=None, scale=SCALE_01):
    """
    Show an image contained in a tensor. The tensor will be reshaped properly, as long as it has the required 28*28 = 784 entries.
    
    If imgname is provided, the image will be saved to a file, otherwise it will be stored in a temporary file and displayed on screen.
    
    The parameter scale can be used to perform one of three scaling operations:
        SCALE_OFF: No scaling is performed, the data is expected to use values between 0 and 255
        SCALE_RANGE: The data will be rescaled from whichever scale it has to be between 0 and 255. This is useful for data in an unknown/arbitrary range. The lowest value present in the data will be 
        converted to 0, the highest to 255, and all intermediate values will be assigned using linear interpolation
        SCALE_01: The data will be rescaled from a range between 0 and 1 to the range between 0 and 255. This can be useful if you normalize your data into that range.
    """
    r = tens.max() - tens.min()
    img = PIL.Image.new("L", (28,28))
    scaled = tens
    if scale == SCALE_RANGE:
        scaled = (tens - tens.min())*255/r
    elif scale == SCALE_01:
        scaled = tens*255
    img.putdata(to_list(scaled))
    if imgname is None:
        img.show()
    else:
        img.save(imgname)

# Used for both tasks
loss_fn = torch.nn.BCELoss()

# TODO 3
# Change Network architecture of the discriminator/classifier network. It should have 784 inputs and 1 output (0 = fake, 1 = real)
class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.h=nn.Sequential(
            nn.Linear(784,512),
            nn.LeakyReLU(0.01),
            nn.Linear(512,256),
            nn.LeakyReLU(0.01),
            nn.Linear(256,1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
      return self.h(x)

# TODO 4
# Implement training loop for the classifier:
# for i in range(n0):
#     zero gradients
#     calculate predictions for given x
#     calculate loss, comparing the predictions with the given y
#     calculate the gradient (loss.backward())
#     print i and the loss
#     perform an optimizer step

def train_classifier(opt, model, x, y):
   for i in range(n0):
        
        opt.zero_grad()

        y_hat=model(x)

        loss=loss_fn(y_hat,y)

        loss.backward()
        
        opt.step()

        print(i," loss is:",torch.tensor(loss))

# TODO 5
# Instantiate the network and the optimizer
# call train_classifier with the training set
# Calculate metrics on the validation set 
# Example: 
#      y_pred = net(x_validation[labels_validation == 3]) calculates all predictions for all images we know to be 3s
#      (y_pred > 0.5) is a tensor that tells you if a given image was classified as your chosen digit (True) or not (False)
#      You can convert this tensor to 0s and 1s by calling .float()
#      (y_pred > 0.5).sum() will tell you how many of these predictions were true
# You are supposed to calculate:
#     For each digit from 0 to 9, which number percentage of images that were of that digit were predicted as your chosen digit
#     The percentage of digits that were classified correctly (i.e. that were your digit and predicted as such, or were another digit and not predicted as your digit)
#     This last value (accuracy) should be over 90%
#     Precision (which percentage of images identified as your chosen digit was actually that digit: TP/(TP+FP))
#     Recall (which percentage of your chosen digit was identified as such: TP/(TP+FN))
def classify(x_train, y_train, x_validation, labels_validation):

  model=Discriminator()
  optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

  train_classifier(optimizer,model,x_train,y_train)

  TP, TN, FP, FN = 0, 0, 0, 0
  falsepositives = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  for i in range(10):
    y_pred = model(x_validation[labels_validation == i])

    if digit == i:
      TP += (y_pred > 0.5).sum()
      FN += (y_pred < 0.5).sum()

    else:
      FP += (y_pred > 0.5).sum()
      falsepositives[i] += (y_pred > 0.5).sum()
      TN += (y_pred < 0.5).sum()

  print("TP: ", TP)
  print("TN: ", TN)
  print("FP: ", FP)
  print("FN: ", FN)

  accuracy = (TP + TN)/(TP + FP + TN + FN)
  precision = (TP)/(TP + FP)
  recall = (TP)/(TP + FN)
  F1 = (2 * precision * recall)/(precision + recall)

  print("Accuracy: ", accuracy)
  print("Precision: ", precision)
  print("Recall: ", recall)
  print("F1: ", F1)

  max = 0
  maxindex = 0;

  print("False Positives:")
  for i in range(10):
    print(i, ": ", falsepositives[i])
    if falsepositives[i] > max:
      max = falsepositives[i]
      maxindex = i;

  print(maxindex)
  y_pred = model(x_validation[labels_validation == maxindex])

  indices = []

  for i in range(y_pred.size()[0]):
    if (y_pred[i] > 0.5):
      indices.append(i)

  check=x_validation[labels_validation == maxindex]
  for i in indices:
    show_image(check[i], "classify_sample_%d.png"%(i), scale=SCALE_01)

# Task 2 (GAN) starts here

# TODO 6: Change number of total training iterations for GAN, for the discriminator and for the generator
n = 15
n1 = 30
n2 = 40

# TODO 7
# Change Network architecture of the generator network. It should have 100 inputs (will be random numbers) and 784 outputs 
# (one for each pixel, each between 0 and 1)

class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.h= nn.Sequential(
            nn.Linear(100,256),
            nn.LeakyReLU(0.01),
            nn.Linear(256,512),
            nn.LeakyReLU(0.01),
            nn.Linear(512,784)
        )
      
    def forward(self, x):
        return self.h(x)

# TODO 8
# Implement training loop for the discriminator, given real and fake data:
# for i in range(n1):
#     zero gradients
#     calculate predictions for the x known as real 
#     calculate loss, comparing the predictions with a tensor consisting of 1s (we want all of these samples to be classified as real)
#     calculate the gradient (loss_true.backward())
#     calculate predictions for the x known as fake
#     calculate loss, comparing the predictions with a tensor consisting of 0s (we want all of these samples to be classified as fake)
#     calculate the gradient (loss_false.backward())
#     print i and both of the loss values
#     perform an optimizer step
def train_discriminator(opt, discriminator, x_true, x_false):
    for i in range(n1):

      opt.zero_grad()
      

      y_hat = discriminator(x_true)
      loss_real = loss_fn(y_hat,torch.ones_like(y_hat))
      loss_real.backward()

      y_hat = discriminator(x_false)
      loss_fake = loss_fn(y_hat, torch.zeros_like(y_hat))
      loss_fake.backward()
  
      opt.step()
      print(i ," loss for real:" , torch.tensor(loss_real)," loss for fake:",torch.tensor(loss_fake) )

# TODO 9 
# Implement training loop for the generator:
# for i in range(n2):
#     zero gradients 
#     generate some random inputs
#     calculate generated images by passing these inputs to the generator
#     pass the generated images to the discriminator to predict if they are true or fake
#     calculate the loss, comparing the predictions with a tensor of 1s (the *generator* wants the discriminator to classify its images as real)
#     calculate the gradient (loss.backward())
#     print i and the loss
#     perform an optimization step
def train_generator(opt, generator, discriminator):
    for i in range(n2):

      opt.zero_grad()

      x_fake = torch.rand(100,100)
      
      fake=generator(x_fake)

      output=discriminator(fake)

      loss=loss_fn(output,torch.ones_like(output))
      loss.backward()
      opt.step()
      print(i," loss for generator ",torch.tensor(loss))

# TODO 10
# Implement GAN training loop:
# Generate some random images (with torch.rand) as an initial collection of fakes
# Instantiate the two networks and two optimizers (one for each network!)
# for i in range(n):
#    call train_discriminator with the given real images and the collection of fake images 
#    call train_generator 
#    generate some images with the current generator, and add a random selection of old fake images (e.g. 100 random old ones, and 100new ones = 200 in total)
#    this will be your new collection of fake images
#    save some of the current fake images to files (use a filename like "sample_%d_%d.png"%(i,j) so you have some samples from each iteration so you can see if the network improves)
# If you read the todos above, your training code will print the loss in each iteration. The loss for the discriminator and the generator should decrease each time their respective training functions are called 
# The images should start to look like numbers after just a few (could be after 1 or 2 already, or 3-10) iterations of *this* loop
def gan(x_real):

  disc = Discriminator()
  opt1 = torch.optim.Adam(disc.parameters(), lr=0.001)
    
  gen = Generator()
  opt2 = torch.optim.Adam(gen.parameters(),lr=0.0001)
  
  x_false=torch.rand(100,784)
  
  for i in range(n):
    print("the ",i," iteration")
    train_discriminator(opt1, disc, x_real, x_false)
    train_generator(opt2, gen, disc) 

    new_fake=torch.rand(100,100)
    new_fake=gen(new_fake)

    x_false=torch.cat((x_false,new_fake))
    x_false=x_false.detach()

    show_image(new_fake[0], "sample_%d.png"%(i), scale=SCALE_01)

def main(rungan):

  train = torchvision.datasets.MNIST(".", download=True)
  x_train = train.data.float().view(-1,28*28)/255.0
  labels_train = train.targets
  y_train = (labels_train == digit).float().view(-1,1)

  validation = torchvision.datasets.MNIST(".", train=False)
  x_validation = validation.data.float().view(-1,28*28)/255.0
  labels_validation = validation.targets

  if rungan:
        gan(x_train[labels_train == digit])
  else:
        classify(x_train, y_train, x_validation, labels_validation)
"""
You can pass -g or --gan to the script to run the GAN part, otherwise it will run the classification part.
"""
if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Train a classifier or a GAN on the MNIST data.')
    parser.add_argument('--gan', '-g', dest='gan', action='store_const',
                        const=True, default=False,
                        help='Train and run the GAN (default: train and run the classifier only)')

    args = parser.parse_args(['-g'])
    main(args.gan)